version: '3.8'
services:
    # -------------------------
    # NODO 1: PRIMARIO
    # -------------------------
    node1:
        image: postgres:17
        container_name: db-node1
        restart: unless-stopped
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            TZ: "UTC"
        volumes:
            - node1_data:/var/lib/postgresql/data
            # AQUÍ INYECTAS TU TRABAJO:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
        # Obligas al nodo a arrancar con tu configuración
        command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
        networks:
            - cluster-net

    # -------------------------
    # NODO 2 y 3: SECUNDARIOS
    # -------------------------
    node2:
        image: postgres:17
        container_name: db-node2
        restart: unless-stopped
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - node2_data:/var/lib/postgresql/data
        networks:
            - cluster-net

    node3:
        image: postgres:17
        container_name: db-node3
        restart: unless-stopped
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - node3_data:/var/lib/postgresql/data
        networks:
            - cluster-net

    # -------------------------
    # PROXY (Trabajo de Persona 1 intacto)
    # -------------------------
    haproxy:
        image: haproxy:3.4.4
        container_name: haproxy-lib
        ports: 
        - "5000:5000"
        - "5001:5001"
        - "8404:8404"
        volumes:
            - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        networks:
            - cluster-net
        depends_on:
            - node1

volumes:
    node1_data:
    node2_data:
    node3_data:

networks:
    cluster-net:
        driver: bridge