version: '3.8'
services:
    node1:
        image: postgres:17
        container_name: db-node1
        restart: unless-stopped
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            # ---- sin puerto---
            # -----
        # ---- volumen -----
        volumes:
            - node1_data:/var/lib/postgresql/data
        # --------
        # ---- red -----
        networks:
        - cluster-net
        # -----------
        # ----- agregar contendor haproxy ------
    haproxy:
        image: haproxy:3.4.4
        container_name: haproxy-lib
        ports: 
        - "5000:5000"
        - "5001:5001"
        - "8404:8404"
        volumes:
            - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        networks:
            - cluster-net
        # ---- indica que depende de node1 para que arranque en orden----
        depends_on:
            - node1


        # -----------------
# ---- secciones globales-------
volumes:
    node1_data:

networks:
    cluster-net:
            driver: bridge


