local   all             all                                     trust
host    all             all             0.0.0.0/0               scram-sha-256
# Permiso especial para que el nodo 2 y 3 puedan clonar la base:
#host    replication     usuario_replicacion      172.19.0.0/16      md5
host      replication     usuario_replicacion      0.0.0.0/0              scram-sha-256   #para que el nodo primario no rechace 

#a los nodos 2 y 3 si docker les da una ip distinta
